version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: financial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Coolboy455!!
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn financial_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
